-- Soften Performance Hub V2.27.0
-- Qualidade independente do technician_monthly.
-- Permite manter Produto/Empresa de tecnicos que nao aparecem no CSV operacional da competencia.

begin;

create table if not exists public.quality_person_daily_metrics (
  id bigint generated by default as identity primary key,
  squad_month_id uuid not null references public.squad_months(id) on delete cascade,
  technician_name text not null,
  technician_key text not null,
  day integer not null check (day between 1 and 31),
  quality_type text not null check (quality_type in ('product','company')),
  notes5 integer not null default 0 check (notes5 >= 0),
  notes4 integer not null default 0 check (notes4 >= 0),
  notes3 integer not null default 0 check (notes3 >= 0),
  notes2 integer not null default 0 check (notes2 >= 0),
  notes1 integer not null default 0 check (notes1 >= 0),
  source_file text,
  imported_by uuid null,
  imported_at timestamptz not null default now(),
  constraint quality_person_daily_metrics_unique unique (squad_month_id, technician_key, day, quality_type)
);

create index if not exists idx_quality_person_daily_month
  on public.quality_person_daily_metrics (squad_month_id);

create index if not exists idx_quality_person_daily_tech
  on public.quality_person_daily_metrics (squad_month_id, technician_key);

create index if not exists idx_quality_person_daily_type_day
  on public.quality_person_daily_metrics (quality_type, day);

comment on table public.quality_person_daily_metrics is
'Qualidade Produto/Empresa por tecnico e dia, independente de existir linha operacional em technician_monthly.';

-- Preserva dados ja importados na V2.26. A proxima reimportacao da qualidade
-- substitui integralmente os registros da competencia/squad nesta nova tabela.
insert into public.quality_person_daily_metrics (
  squad_month_id, technician_name, technician_key, day, quality_type,
  notes5, notes4, notes3, notes2, notes1, source_file, imported_by, imported_at
)
select
  tm.squad_month_id,
  tm.technician_name,
  lower(regexp_replace(trim(tm.technician_name), '[[:space:]]+', '', 'g')),
  q.day,
  q.quality_type,
  q.notes5, q.notes4, q.notes3, q.notes2, q.notes1,
  q.source_file, q.imported_by, q.imported_at
from public.quality_daily_metrics q
join public.technician_monthly tm on tm.id = q.technician_month_id
on conflict (squad_month_id, technician_key, day, quality_type)
do update set
  technician_name = excluded.technician_name,
  notes5 = excluded.notes5,
  notes4 = excluded.notes4,
  notes3 = excluded.notes3,
  notes2 = excluded.notes2,
  notes1 = excluded.notes1,
  source_file = excluded.source_file,
  imported_by = excluded.imported_by,
  imported_at = excluded.imported_at;

alter table public.quality_person_daily_metrics enable row level security;

drop policy if exists quality_person_daily_select on public.quality_person_daily_metrics;
create policy quality_person_daily_select on public.quality_person_daily_metrics
for select to authenticated
using (
  exists (
    select 1
    from public.squad_months sm
    where sm.id = quality_person_daily_metrics.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists quality_person_daily_insert on public.quality_person_daily_metrics;
create policy quality_person_daily_insert on public.quality_person_daily_metrics
for insert to authenticated
with check (
  exists (
    select 1
    from public.squad_months sm
    where sm.id = quality_person_daily_metrics.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists quality_person_daily_update on public.quality_person_daily_metrics;
create policy quality_person_daily_update on public.quality_person_daily_metrics
for update to authenticated
using (
  exists (
    select 1
    from public.squad_months sm
    where sm.id = quality_person_daily_metrics.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
)
with check (
  exists (
    select 1
    from public.squad_months sm
    where sm.id = quality_person_daily_metrics.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists quality_person_daily_delete on public.quality_person_daily_metrics;
create policy quality_person_daily_delete on public.quality_person_daily_metrics
for delete to authenticated
using (
  exists (
    select 1
    from public.squad_months sm
    where sm.id = quality_person_daily_metrics.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

grant select, insert, update, delete on public.quality_person_daily_metrics to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
