-- Soften Performance Hub V2.29.0
-- Impacto financeiro da qualidade sem armazenar clientes individualmente.
-- Cada CSV deve vir previamente deduplicado: uma linha valida = um cliente unico na competencia.

begin;

create table if not exists public.quality_financial_monthly (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  year int not null check (year between 2020 and 2100),
  month int not null check (month between 1 and 12),
  active_clients int not null default 0 check (active_clients >= 0),
  avg_ticket numeric(14,2) not null default 0 check (avg_ticket >= 0),
  evaluated_clients int not null default 0 check (evaluated_clients >= 0),
  risk_any_clients int not null default 0 check (risk_any_clients >= 0),
  service_n1 int not null default 0 check (service_n1 >= 0),
  service_n2 int not null default 0 check (service_n2 >= 0),
  service_n3 int not null default 0 check (service_n3 >= 0),
  service_n4 int not null default 0 check (service_n4 >= 0),
  service_n5 int not null default 0 check (service_n5 >= 0),
  product_n1 int not null default 0 check (product_n1 >= 0),
  product_n2 int not null default 0 check (product_n2 >= 0),
  product_n3 int not null default 0 check (product_n3 >= 0),
  product_n4 int not null default 0 check (product_n4 >= 0),
  product_n5 int not null default 0 check (product_n5 >= 0),
  company_n1 int not null default 0 check (company_n1 >= 0),
  company_n2 int not null default 0 check (company_n2 >= 0),
  company_n3 int not null default 0 check (company_n3 >= 0),
  company_n4 int not null default 0 check (company_n4 >= 0),
  company_n5 int not null default 0 check (company_n5 >= 0),
  source_file text null,
  imported_by uuid null references auth.users(id) on delete set null,
  imported_at timestamptz null,
  updated_by uuid null references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint quality_financial_monthly_unique unique (organization_id, year, month),
  constraint quality_financial_risk_le_evaluated check (risk_any_clients <= evaluated_clients)
);

create index if not exists idx_quality_financial_monthly_period
  on public.quality_financial_monthly (organization_id, year, month);

comment on table public.quality_financial_monthly is
'Consolidado mensal do Impacto Financeiro da Qualidade. Nao armazena cliente, nome ou CNPJ. Guarda apenas parametros da carteira e contagens agregadas do CSV previamente deduplicado.';

comment on column public.quality_financial_monthly.risk_any_clients is
'Clientes unicos com pelo menos uma nota de 1 a 3 em Servico, Produto ou Empresa; cada cliente conta no maximo uma vez neste campo.';

alter table public.quality_financial_monthly enable row level security;

drop policy if exists quality_financial_monthly_select on public.quality_financial_monthly;
create policy quality_financial_monthly_select on public.quality_financial_monthly
for select to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists quality_financial_monthly_insert on public.quality_financial_monthly;
create policy quality_financial_monthly_insert on public.quality_financial_monthly
for insert to authenticated
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists quality_financial_monthly_update on public.quality_financial_monthly;
create policy quality_financial_monthly_update on public.quality_financial_monthly
for update to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
)
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists quality_financial_monthly_delete on public.quality_financial_monthly;
create policy quality_financial_monthly_delete on public.quality_financial_monthly
for delete to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

grant select, insert, update, delete on public.quality_financial_monthly to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
