-- Soften Performance Hub V2.28.1
-- Simplifica a base de custos: custo geral mensal do Suporte, sem valores individuais por tecnico.
-- A tabela da V2.28.0 e mantida apenas por compatibilidade/historico e deixa de ser usada pela tela.

begin;

create table if not exists public.support_monthly_costs (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  year int not null check (year between 2020 and 2100),
  month int not null check (month between 1 and 12),
  payroll_cost numeric(14,2) not null default 0 check (payroll_cost >= 0),
  other_costs numeric(14,2) not null default 0 check (other_costs >= 0),
  technician_count int not null default 1 check (technician_count >= 1),
  hours_per_day numeric(5,2) not null default 8 check (hours_per_day > 0 and hours_per_day <= 24),
  updated_by uuid null references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint support_monthly_costs_unique unique (organization_id, year, month)
);

create index if not exists idx_support_monthly_costs_period
  on public.support_monthly_costs (organization_id, year, month);

comment on table public.support_monthly_costs is
'Base confidencial de custo geral mensal do Suporte tecnico. Armazena custo com pagamentos, outros custos, quantidade total de tecnicos e horas uteis por dia.';

alter table public.support_monthly_costs enable row level security;

drop policy if exists support_monthly_costs_select on public.support_monthly_costs;
create policy support_monthly_costs_select on public.support_monthly_costs
for select to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists support_monthly_costs_insert on public.support_monthly_costs;
create policy support_monthly_costs_insert on public.support_monthly_costs
for insert to authenticated
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists support_monthly_costs_update on public.support_monthly_costs;
create policy support_monthly_costs_update on public.support_monthly_costs
for update to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
)
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists support_monthly_costs_delete on public.support_monthly_costs;
create policy support_monthly_costs_delete on public.support_monthly_costs
for delete to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

grant select, insert, update, delete on public.support_monthly_costs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

do $$
begin
  if to_regclass('public.support_technician_hourly_costs') is not null then
    comment on table public.support_technician_hourly_costs is
    'LEGADO V2.28.0: base individual de custo-hora por tecnico. Mantida por compatibilidade, mas a tela Custos da V2.28.1 nao utiliza esta tabela.';
  end if;
end $$;

commit;
