-- Soften Performance Hub V2.26.0
-- Qualidade: importacao independente de notas de Produto/Empresa por tecnico/dia.
-- A coluna NotaServico do CSV de qualidade nao e armazenada nem utilizada em calculos.

begin;

create table if not exists public.quality_daily_metrics (
  id bigint generated by default as identity primary key,
  technician_month_id uuid not null references public.technician_monthly(id) on delete cascade,
  day integer not null check (day between 1 and 31),
  quality_type text not null check (quality_type in ('product','company')),
  notes5 integer not null default 0 check (notes5 >= 0),
  notes4 integer not null default 0 check (notes4 >= 0),
  notes3 integer not null default 0 check (notes3 >= 0),
  notes2 integer not null default 0 check (notes2 >= 0),
  notes1 integer not null default 0 check (notes1 >= 0),
  source_file text,
  imported_by uuid null,
  imported_at timestamptz not null default now(),
  constraint quality_daily_metrics_unique unique (technician_month_id, day, quality_type)
);

create index if not exists idx_quality_daily_metrics_tech_month
  on public.quality_daily_metrics (technician_month_id);

create index if not exists idx_quality_daily_metrics_type
  on public.quality_daily_metrics (quality_type, day);

comment on table public.quality_daily_metrics is 'Consolidado diario das avaliacoes de Produto e Empresa. Servico continua exclusivamente em daily_metrics.';
comment on column public.quality_daily_metrics.quality_type is 'product ou company. NotaServico do CSV de qualidade e ignorada pelo frontend.';

alter table public.quality_daily_metrics enable row level security;

drop policy if exists quality_daily_select on public.quality_daily_metrics;
create policy quality_daily_select on public.quality_daily_metrics
for select to authenticated
using (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and (
        tm.user_id = (select auth.uid())
        or public.can_admin_squad(sm.squad_id)
      )
  )
);

drop policy if exists quality_daily_insert on public.quality_daily_metrics;
create policy quality_daily_insert on public.quality_daily_metrics
for insert to authenticated
with check (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists quality_daily_update on public.quality_daily_metrics;
create policy quality_daily_update on public.quality_daily_metrics
for update to authenticated
using (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
)
with check (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists quality_daily_delete on public.quality_daily_metrics;
create policy quality_daily_delete on public.quality_daily_metrics
for delete to authenticated
using (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = quality_daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

grant select, insert, update, delete on public.quality_daily_metrics to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
