-- Soften Performance Hub V2.28.0
-- Base historica e confidencial de custo-hora do suporte tecnico.
-- Escopo organizacional: nao pertence a um Squad.

begin;

create table if not exists public.support_technician_hourly_costs (
  id bigint generated by default as identity primary key,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  technician_user_id uuid null,
  technician_name text not null,
  technician_key text not null,
  year int not null check (year between 2020 and 2100),
  month int not null check (month between 1 and 12),
  hourly_cost numeric(12,2) not null default 0 check (hourly_cost >= 0),
  updated_by uuid null references auth.users(id) on delete set null,
  updated_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  constraint support_technician_hourly_costs_unique unique (organization_id, year, month, technician_key)
);

create index if not exists idx_support_hourly_costs_period
  on public.support_technician_hourly_costs (organization_id, year, month);

create index if not exists idx_support_hourly_costs_technician
  on public.support_technician_hourly_costs (organization_id, technician_key, year, month);

comment on table public.support_technician_hourly_costs is
'Base historica confidencial de custo-hora por tecnico e competencia. Uso futuro em analises de custo de atendimento do suporte como um todo.';

alter table public.support_technician_hourly_costs enable row level security;

drop policy if exists support_hourly_costs_select on public.support_technician_hourly_costs;
create policy support_hourly_costs_select on public.support_technician_hourly_costs
for select to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists support_hourly_costs_insert on public.support_technician_hourly_costs;
create policy support_hourly_costs_insert on public.support_technician_hourly_costs
for insert to authenticated
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists support_hourly_costs_update on public.support_technician_hourly_costs;
create policy support_hourly_costs_update on public.support_technician_hourly_costs
for update to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
)
with check (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

drop policy if exists support_hourly_costs_delete on public.support_technician_hourly_costs;
create policy support_hourly_costs_delete on public.support_technician_hourly_costs
for delete to authenticated
using (
  public.is_super_admin()
  and organization_id = (select (public.current_profile()).organization_id)
);

grant select, insert, update, delete on public.support_technician_hourly_costs to authenticated;
grant usage, select on all sequences in schema public to authenticated;

commit;
