-- SOFTEN PERFORMANCE HUB V2.1.1
-- Estrutura multi-squad preparada para Supabase/PostgreSQL.
-- Execute este arquivo no SQL Editor de um projeto Supabase novo.

create extension if not exists pgcrypto;

create table if not exists public.organizations (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.squads (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations(id) on delete cascade,
  code text not null,
  name text not null,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  unique (organization_id, code)
);

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  organization_id uuid not null references public.organizations(id) on delete cascade,
  squad_id uuid references public.squads(id) on delete set null,
  full_name text not null,
  email text,
  role text not null check (role in ('super_admin','squad_admin','technician')),
  technician_name text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  check (role <> 'technician' or (squad_id is not null and technician_name is not null)),
  check (role <> 'squad_admin' or squad_id is not null)
);

-- Compatibilidade ao executar esta versão sobre uma base V2.0.x existente.
alter table public.profiles add column if not exists email text;

create table if not exists public.squad_months (
  id uuid primary key default gen_random_uuid(),
  squad_id uuid not null references public.squads(id) on delete cascade,
  year int not null check (year between 2020 and 2100),
  month int not null check (month between 1 and 12),
  source_file text,
  latest_day int not null default 1 check (latest_day between 1 and 31),
  team_result text,
  redistributed numeric(12,2) not null default 0,
  team_goal_att numeric(12,2),
  team_goal_eval_pct numeric(8,6) not null default 0.343,
  imported_by uuid references auth.users(id) on delete set null,
  imported_at timestamptz not null default now(),
  unique (squad_id, year, month)
);

create table if not exists public.technician_monthly (
  id uuid primary key default gen_random_uuid(),
  squad_month_id uuid not null references public.squad_months(id) on delete cascade,
  user_id uuid references auth.users(id) on delete set null,
  technician_name text not null,
  att numeric(12,2) not null default 0,
  notes5 numeric(12,2) not null default 0,
  notes4 numeric(12,2) not null default 0,
  notes3 numeric(12,2) not null default 0,
  notes2 numeric(12,2) not null default 0,
  notes1 numeric(12,2) not null default 0,
  total_eval numeric(12,2) not null default 0,
  avg_rating numeric(8,4) not null default 0,
  eval_pct numeric(8,6) not null default 0,
  status text,
  goals_hit int not null default 0,
  points numeric(14,2) not null default 0,
  rank int,
  discount numeric(14,2) not null default 0,
  point_bonus numeric(14,2) not null default 0,
  goal_att numeric(12,2) not null default 0,
  goal_eval numeric(12,2) not null default 0,
  unique (squad_month_id, technician_name)
);

create table if not exists public.daily_metrics (
  id bigint generated by default as identity primary key,
  technician_month_id uuid not null references public.technician_monthly(id) on delete cascade,
  day int not null check (day between 1 and 31),
  att numeric(12,2) not null default 0,
  notes5 numeric(12,2) not null default 0,
  off boolean not null default false,
  unique (technician_month_id, day)
);

create table if not exists public.squad_themes (
  squad_id uuid primary key references public.squads(id) on delete cascade,
  theme jsonb not null default '{}'::jsonb,
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create index if not exists idx_profiles_squad on public.profiles(squad_id);
create unique index if not exists idx_profiles_org_email_unique on public.profiles(organization_id, lower(email)) where email is not null;
create index if not exists idx_squad_months_squad on public.squad_months(squad_id);
create index if not exists idx_technician_monthly_month on public.technician_monthly(squad_month_id);
create index if not exists idx_technician_monthly_user on public.technician_monthly(user_id);
create index if not exists idx_daily_metrics_tech_month on public.daily_metrics(technician_month_id);

-- Helpers de autorizacao. SECURITY DEFINER evita recursao de RLS ao consultar profiles.
create or replace function public.current_profile()
returns public.profiles
language sql
stable
security definer
set search_path = public
as $$
  select p from public.profiles p
  where p.user_id = (select auth.uid()) and p.active = true
  limit 1;
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.profiles p
    where p.user_id = (select auth.uid())
      and p.active = true
      and p.role = 'super_admin'
  );
$$;

create or replace function public.can_read_squad(target_squad uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    join public.squads s on s.id = target_squad
    where p.user_id = (select auth.uid())
      and p.active = true
      and p.organization_id = s.organization_id
      and (
        p.role = 'super_admin'
        or p.squad_id = target_squad
      )
  );
$$;

create or replace function public.can_admin_squad(target_squad uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.profiles p
    join public.squads s on s.id = target_squad
    where p.user_id = (select auth.uid())
      and p.active = true
      and p.organization_id = s.organization_id
      and (
        p.role = 'super_admin'
        or (p.role = 'squad_admin' and p.squad_id = target_squad)
      )
  );
$$;

revoke all on function public.current_profile() from public;
revoke all on function public.is_super_admin() from public;
revoke all on function public.can_read_squad(uuid) from public;
revoke all on function public.can_admin_squad(uuid) from public;
grant execute on function public.current_profile() to authenticated;
grant execute on function public.is_super_admin() to authenticated;
grant execute on function public.can_read_squad(uuid) to authenticated;
grant execute on function public.can_admin_squad(uuid) to authenticated;

-- RLS
alter table public.organizations enable row level security;
alter table public.squads enable row level security;
alter table public.profiles enable row level security;
alter table public.squad_months enable row level security;
alter table public.technician_monthly enable row level security;
alter table public.daily_metrics enable row level security;
alter table public.squad_themes enable row level security;

-- Organizations: usuario ve apenas a propria organizacao.
drop policy if exists org_select on public.organizations;
create policy org_select on public.organizations
for select to authenticated
using (id = (select (public.current_profile()).organization_id));

-- Squads: tecnico/admin do squad ve apenas o seu; super_admin ve todos da organizacao.
drop policy if exists squads_select on public.squads;
create policy squads_select on public.squads
for select to authenticated
using (public.can_read_squad(id));

-- Profiles: usuario ve o proprio perfil; admins podem ver perfis dentro do escopo que administram.
drop policy if exists profiles_select on public.profiles;
create policy profiles_select on public.profiles
for select to authenticated
using (
  user_id = (select auth.uid())
  or (squad_id is not null and public.can_admin_squad(squad_id))
  or (public.is_super_admin() and organization_id = (select (public.current_profile()).organization_id))
);

-- A criação cotidiana de usuários é feita pela Edge Function create-user com service_role.
-- Estas policies mantêm uma barreira adicional; a Data API do navegador recebe apenas SELECT em profiles.
-- Edicao direta de profiles fica reservada ao admin geral por seguranca.
drop policy if exists profiles_insert on public.profiles;
create policy profiles_insert on public.profiles
for insert to authenticated
with check (public.is_super_admin());

drop policy if exists profiles_update on public.profiles;
create policy profiles_update on public.profiles
for update to authenticated
using (public.is_super_admin())
with check (public.is_super_admin());

-- Meses do squad.
drop policy if exists squad_months_select on public.squad_months;
create policy squad_months_select on public.squad_months
for select to authenticated
using (public.can_read_squad(squad_id));

drop policy if exists squad_months_insert on public.squad_months;
create policy squad_months_insert on public.squad_months
for insert to authenticated
with check (public.can_admin_squad(squad_id));

drop policy if exists squad_months_update on public.squad_months;
create policy squad_months_update on public.squad_months
for update to authenticated
using (public.can_admin_squad(squad_id))
with check (public.can_admin_squad(squad_id));

drop policy if exists squad_months_delete on public.squad_months;
create policy squad_months_delete on public.squad_months
for delete to authenticated
using (public.can_admin_squad(squad_id));

-- Resultados mensais: qualquer membro do mesmo Squad pode ver o ranking mensal.
drop policy if exists tech_month_select on public.technician_monthly;
create policy tech_month_select on public.technician_monthly
for select to authenticated
using (
  exists (
    select 1 from public.squad_months sm
    where sm.id = technician_monthly.squad_month_id
      and public.can_read_squad(sm.squad_id)
  )
);

drop policy if exists tech_month_insert on public.technician_monthly;
create policy tech_month_insert on public.technician_monthly
for insert to authenticated
with check (
  exists (
    select 1 from public.squad_months sm
    where sm.id = technician_monthly.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists tech_month_update on public.technician_monthly;
create policy tech_month_update on public.technician_monthly
for update to authenticated
using (
  exists (
    select 1 from public.squad_months sm
    where sm.id = technician_monthly.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
)
with check (
  exists (
    select 1 from public.squad_months sm
    where sm.id = technician_monthly.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists tech_month_delete on public.technician_monthly;
create policy tech_month_delete on public.technician_monthly
for delete to authenticated
using (
  exists (
    select 1 from public.squad_months sm
    where sm.id = technician_monthly.squad_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

-- Dia a dia: tecnico ve apenas o proprio detalhe. Admin do Squad ve todos do seu Squad.
drop policy if exists daily_select on public.daily_metrics;
create policy daily_select on public.daily_metrics
for select to authenticated
using (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = daily_metrics.technician_month_id
      and (
        tm.user_id = (select auth.uid())
        or public.can_admin_squad(sm.squad_id)
      )
  )
);

drop policy if exists daily_insert on public.daily_metrics;
create policy daily_insert on public.daily_metrics
for insert to authenticated
with check (
  exists (
    select 1
    from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists daily_update on public.daily_metrics;
create policy daily_update on public.daily_metrics
for update to authenticated
using (
  exists (
    select 1 from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
)
with check (
  exists (
    select 1 from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

drop policy if exists daily_delete on public.daily_metrics;
create policy daily_delete on public.daily_metrics
for delete to authenticated
using (
  exists (
    select 1 from public.technician_monthly tm
    join public.squad_months sm on sm.id = tm.squad_month_id
    where tm.id = daily_metrics.technician_month_id
      and public.can_admin_squad(sm.squad_id)
  )
);

-- Temas: todos do Squad leem; somente admins alteram.
drop policy if exists themes_select on public.squad_themes;
create policy themes_select on public.squad_themes
for select to authenticated
using (public.can_read_squad(squad_id));

drop policy if exists themes_insert on public.squad_themes;
create policy themes_insert on public.squad_themes
for insert to authenticated
with check (public.can_admin_squad(squad_id));

drop policy if exists themes_update on public.squad_themes;
create policy themes_update on public.squad_themes
for update to authenticated
using (public.can_admin_squad(squad_id))
with check (public.can_admin_squad(squad_id));

drop policy if exists themes_delete on public.squad_themes;
create policy themes_delete on public.squad_themes
for delete to authenticated
using (public.can_admin_squad(squad_id));

-- Permissoes da Data API. RLS continua sendo a camada que limita as linhas.
grant usage on schema public to authenticated;
grant select on public.organizations, public.squads to authenticated;
revoke insert, update, delete on public.profiles from authenticated;
grant select on public.profiles to authenticated;
grant select, insert, update, delete on public.squad_months to authenticated;
grant select, insert, update, delete on public.technician_monthly to authenticated;
grant select, insert, update, delete on public.daily_metrics to authenticated;
grant select, insert, update, delete on public.squad_themes to authenticated;
grant usage, select on all sequences in schema public to authenticated;

-- Estrutura inicial: Soften + 4 Squads.
insert into public.organizations (id,name,slug)
values ('10000000-0000-0000-0000-000000000001','Soften Sistemas','soften-sistemas')
on conflict (slug) do update set name=excluded.name;

insert into public.squads (id,organization_id,code,name)
values
 ('20000000-0000-0000-0000-00000000000a','10000000-0000-0000-0000-000000000001','A','Squad A'),
 ('20000000-0000-0000-0000-00000000000b','10000000-0000-0000-0000-000000000001','B','Squad B'),
 ('20000000-0000-0000-0000-00000000000d','10000000-0000-0000-0000-000000000001','D','Squad D'),
 ('20000000-0000-0000-0000-00000000000e','10000000-0000-0000-0000-000000000001','E','Squad E')
on conflict (organization_id,code) do update set name=excluded.name, active=true;
